name: Continuous Integration

on:
  push:
    branches:
      - main
      - jenk
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  ci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Show Java version
        run: java -version

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Show directory
        run: pwd

      - name: List files
        run: ls -al

      - name: Install Dependencies
        run: mvn compile

      - name: Build application
        run: mvn package -DskipTests

      - name: Test application
        run: mvn test

  pr-job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show Java version
        run: java -version

      - name: Show directory
        run: pwd

      - name: List files
        run: ls -al

      - name: Install Dependencies
        run: mvn compile

      - name: Build application
        run: mvn package -DskipTests

      - name: Test application
        run: mvn test

